import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="plane-background w-screen h-screen relative">
        <div className="absolute left-0 top-0 h-full w-full bg-blue opacity-50 -z-10"></div>
        {children}
      </body>
    </html>
  );
}
