import type { Metadata } from "next";
import Navbar from "@/app/_components/navbar/navbarComponent";
import { AuthProvider } from "@/app/_utils/context/auth";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <div className="w-full h-full relative bg-blue pt-9 flex flex-col">
        <div className="flex text-white justify-between w-full px-12">
          <span className="material-icons-outlined !text-3xl !flex items-center cursor-pointer">
            account_circle
          </span>
          <h2 className="font-NAM text-5xl">TREKZ</h2>
          <span className="material-icons-outlined !text-3xl !flex items-center cursor-pointer">
            <Link href="/trips/new">add_circle_outline</Link>
          </span>
        </div>
        <div className="px-12 py-11 flex-grow">{children}</div>
        <Navbar />
      </div>
    </AuthProvider>
  );
}
