import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./style.css";
import { AuthProvider } from "./_utils/context/auth";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen relative ${inter.className}`}>
        <Toaster position="top-center" richColors />
        {children}
      </body>
    </html>
  );
}
